### ISSUE TITLE
Location outside ao. Server fails to respond.

### ISSUE THREAD

**Issue by milovanderlinden** [CodeForEindhoven/open311-api#6]
When the server uses the function to find a handling party for a request and __no handler__ is returned, the server process crashes without sending a response.

```javascript
[31mUnhandled rejection TypeError: Cannot read property 'name' of undefined
at /open311/build/controllers/georeportv2.js:371:36
at /open311/build/controllers/georeportv2.js:38:5
at tryCatcher (/open311/build/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/open311/build/node_modules/bluebird/js/release/promise.js:502:31)
at Promise._settlePromise (/open311/build/node_modules/bluebird/js/release/promise.js:559:18)
at Promise._settlePromise0 (/open311/build/node_modules/bluebird/js/release/promise.js:604:10)
at Promise._settlePromises (/open311/build/node_modules/bluebird/js/release/promise.js:683:18)
at Async._drainQueue (/open311/build/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/open311/build/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues [as _onImmediate] (/open311/build/node_modules/bluebird/js/release/async.js:17:14)
at tryOnImmediate (timers.js:543:15)
at processImmediate [as _immediateCallback] (timers.js:523:5)[0m
```

**Comment by milovanderlinden** [comment]
Fixed
